"""Hermetic lock-generator checks; no network, package installs or image runs."""

from __future__ import annotations

import hashlib
import re
import subprocess
from pathlib import Path

import pytest

from workers.build import compile_snapshot_lock as compiler

pytestmark = pytest.mark.unit

EXPECTED = {
    "boto3": "1.43.48",
    "botocore": "1.43.48",
    "greenlet": "3.5.1",
    "jmespath": "1.1.0",
    "psycopg2-binary": "2.9.12",
    "python-dateutil": "2.9.0.post0",
    "s3transfer": "0.19.1",
    "six": "1.17.0",
    "sqlalchemy[asyncio]": "2.0.50",
    "typing-extensions": "4.15.0",
    "urllib3": "2.7.0",
    "pyyaml": "6.0.3",
    "cryptography": "50.0.1",
    "cffi": "2.1.1",
    "pycparser": "3.0",
}


def test_committed_input_and_lock_preserve_exact_dependency_closure() -> None:
    root = Path(__file__).resolve().parents[2]
    for name in ("requirements.in", "requirements.txt"):
        content = (root / "workers/snapshot" / name).read_text()
        entries = re.findall(r"^([a-zA-Z0-9\[\]_.-]+)==([^\s]+)", content, re.MULTILINE)
        assert len(entries) == len(EXPECTED)
        assert {name.lower(): version for name, version in entries} == EXPECTED
        if name.endswith(".txt"):
            assert "--only-binary :all:" in content
            assert "autogenerated by uv" in content
            assert compiler.COMPILE_COMMAND in content
            # Every pinned distribution has at least one real SHA256, no bare pin.
            for block in re.split(r"(?=^[A-Za-z0-9][^\n]*==)", content, flags=re.MULTILINE)[1:]:
                assert re.search(r"--hash=sha256:[0-9a-f]{64}(?:\s|$)", block)


@pytest.mark.parametrize(
    "value",
    [
        "",
        "# only a comment",
        "pkg>=1",
        "-r other.in",
        "--index-url https://elsewhere.invalid",
        "./source",
        "-e .",
        "pkg @ https://elsewhere.invalid/x.whl",
        "pkg==1\npkg==1",
        "Py_Yaml==1\npy-yaml==1",
    ],
)
def test_input_rejects_sources_ranges_directives_and_duplicates(value: str) -> None:
    with pytest.raises(ValueError):
        compiler.validate_input(value)


def test_input_accepts_exact_pins_with_comments_and_extras() -> None:
    compiler.validate_input("# reviewed\npkg[extra]==1.2.0\nOther_Pkg==2.0.post1 # note\n")


def test_compile_command_disallows_builds_and_ambient_resolution(tmp_path: Path) -> None:
    argv = compiler.compile_argv(tmp_path / "uv", tmp_path / "out", tmp_path / "cache")
    assert argv[1:4] == ["--no-config", "pip", "compile"]
    for option, expected in (
        ("--python-version", "3.11"),
        ("--python-platform", "x86_64-unknown-linux-gnu"),
        ("--only-binary", ":all:"),
        ("--default-index", "https://pypi.org/simple"),
        ("--keyring-provider", "disabled"),
        ("--exclude-newer", "2026-09-25T09:49:02Z"),
    ):
        assert argv[argv.index(option) + 1] == expected
    assert "--generate-hashes" in argv and "--emit-build-options" in argv
    assert "--no-python-downloads" in argv
    assert "--no-build" not in argv  # uv rejects combining it with --only-binary.
    assert "--no-deps" not in argv


def test_resolver_environment_does_not_inherit_index_or_build_options(monkeypatch) -> None:
    monkeypatch.setenv("UV_INDEX", "https://elsewhere.invalid")
    monkeypatch.setenv("PIP_INDEX_URL", "https://elsewhere.invalid")
    monkeypatch.setenv("UV_NO_BINARY", ":all:")
    assert set(compiler.resolver_environment()) == {"PATH", "LANG"}


def _controlled_generator(tmp_path: Path, monkeypatch):
    # Mocked resolver tests remain hermetic on every supported test interpreter.
    monkeypatch.setattr(compiler.sys, "version_info", (3, 11, 0))
    uv = tmp_path / "uv"
    uv.write_bytes(b"controlled test executable, never executed")
    monkeypatch.setattr(compiler, "UV_SHA256", hashlib.sha256(uv.read_bytes()).hexdigest())
    monkeypatch.setattr(compiler, "_ROOT", tmp_path)
    source = tmp_path / "workers/snapshot/requirements.in"
    source.parent.mkdir(parents=True)
    source.write_text("example==1.0\n")
    destination = source.with_suffix(".txt")
    destination.write_bytes(b"old lock\n")
    calls = []

    def run(argv, **kwargs):
        calls.append((argv, kwargs))
        if argv[1:] == ["--version"]:
            return subprocess.CompletedProcess(argv, 0, compiler.UV_VERSION + "\n", "")
        Path(argv[argv.index("--output-file") + 1]).write_bytes(b"generated lock\n")
        return subprocess.CompletedProcess(argv, 0, "", "Resolved controlled fixture\n")

    monkeypatch.setattr(compiler.subprocess, "run", run)
    return uv, destination, calls


def test_generate_uses_fresh_output_and_preserves_pins(tmp_path: Path, monkeypatch) -> None:
    uv, destination, calls = _controlled_generator(tmp_path, monkeypatch)
    pins = tmp_path / "workers/pins.json"
    pins.write_bytes(b"unchanged")
    assert compiler.generate(uv, check=False) == hashlib.sha256(b"generated lock\n").hexdigest()
    assert destination.read_bytes() == b"generated lock\n"
    assert pins.read_bytes() == b"unchanged"
    argv, options = calls[1]
    assert Path(argv[argv.index("--output-file") + 1]) != destination
    assert options["cwd"] == tmp_path and options["timeout"] == 300
    assert options["env"] == compiler.resolver_environment()


def test_check_detects_drift_without_rewriting(tmp_path: Path, monkeypatch) -> None:
    uv, destination, _ = _controlled_generator(tmp_path, monkeypatch)
    with pytest.raises(ValueError, match="differs"):
        compiler.generate(uv, check=True)
    assert destination.read_bytes() == b"old lock\n"
    destination.write_bytes(b"generated lock\n")
    assert compiler.generate(uv, check=True) == hashlib.sha256(b"generated lock\n").hexdigest()


def test_wrong_uv_bytes_refuse_before_execution(tmp_path: Path, monkeypatch) -> None:
    uv, destination, calls = _controlled_generator(tmp_path, monkeypatch)
    uv.write_bytes(b"modified executable")
    with pytest.raises(ValueError, match="SHA256"):
        compiler.generate(uv, check=False)
    assert calls == [] and destination.read_bytes() == b"old lock\n"


def test_wrong_uv_version_refuses_resolution(tmp_path: Path, monkeypatch) -> None:
    uv, _, calls = _controlled_generator(tmp_path, monkeypatch)
    original = compiler.subprocess.run

    def wrong_version(argv, **kwargs):
        result = original(argv, **kwargs)
        result.stdout = "uv wrong-version"
        return result

    monkeypatch.setattr(compiler.subprocess, "run", wrong_version)
    with pytest.raises(ValueError, match="version"):
        compiler.generate(uv, check=False)
    assert len(calls) == 1


def test_resolution_failure_does_not_replace_lock(tmp_path: Path, monkeypatch, capsys) -> None:
    uv, destination, _ = _controlled_generator(tmp_path, monkeypatch)
    original = compiler.subprocess.run

    def fail(argv, **kwargs):
        if "compile" in argv:
            raise subprocess.CalledProcessError(2, argv, stderr="controlled resolver failure\n")
        return original(argv, **kwargs)

    monkeypatch.setattr(compiler.subprocess, "run", fail)
    assert compiler.main(["--uv", str(uv)]) == 1
    assert "controlled resolver failure" in capsys.readouterr().err
    assert destination.read_bytes() == b"old lock\n"


def test_generator_refuses_symlink_output(tmp_path: Path, monkeypatch) -> None:
    uv, destination, calls = _controlled_generator(tmp_path, monkeypatch)
    target = tmp_path / "original.txt"
    destination.rename(target)
    destination.symlink_to(target)
    with pytest.raises(ValueError, match="symlink"):
        compiler.generate(uv, check=False)
    assert calls == [] and target.read_bytes() == b"old lock\n"


@pytest.mark.parametrize(
    "relative", ["workers", "workers/snapshot", "workers/snapshot/requirements.in"]
)
def test_generator_refuses_parent_or_input_symlinks(tmp_path: Path, monkeypatch, relative) -> None:
    uv, destination, calls = _controlled_generator(tmp_path, monkeypatch)
    path = tmp_path / relative
    is_directory = path.is_dir()
    target = tmp_path / "outside-checkout-target"
    path.rename(target)
    path.symlink_to(target, target_is_directory=is_directory)
    with pytest.raises(ValueError, match="symlink"):
        compiler.generate(uv, check=False)
    assert calls == [] and destination.read_bytes() == b"old lock\n"


def test_generator_can_create_new_regular_output(tmp_path: Path, monkeypatch) -> None:
    uv, destination, _ = _controlled_generator(tmp_path, monkeypatch)
    destination.unlink()
    compiler.generate(uv, check=False)
    assert destination.read_bytes() == b"generated lock\n"


def test_generator_refuses_non_regular_input(tmp_path: Path, monkeypatch) -> None:
    uv, _, calls = _controlled_generator(tmp_path, monkeypatch)
    source = tmp_path / "workers/snapshot/requirements.in"
    source.unlink()
    source.mkdir()
    with pytest.raises(ValueError, match="regular files"):
        compiler.generate(uv, check=False)
    assert calls == []


def test_generator_refuses_wrong_python_before_execution(tmp_path: Path, monkeypatch) -> None:
    uv, destination, calls = _controlled_generator(tmp_path, monkeypatch)
    monkeypatch.setattr(compiler.sys, "version_info", (3, 12, 0))
    with pytest.raises(ValueError, match=r"Python 3\.11"):
        compiler.generate(uv, check=False)
    assert calls == [] and destination.read_bytes() == b"old lock\n"
